### ISSUE TITLE
neue Versionen im EDIFACT erforderlich, Anpassung Versionsnummern

### ISSUE THREAD

**Issue by frschaul** [tinyheb/tinyheb#4]
https://www.gkv-datenaustausch.de/leistungserbringer/sonstige_leistungserbringer/sonstige_leistungserbringer.jsp

technische Anlage 3 Version 11, Stand 13.03.2017, anzuwenden ab 01.01.2018. Hinweis: Für die Technische Anlage 3 Version 10 Stand 18.02.2016 gilt eine Übergangsfrist von 3 Monaten, d.h. zum 01.04.2018 verliert diese ihre Gültigkeit. Daten werden ab diesem Datum nur noch im Format der Version 11 Stand 13.03.2017 angenommen. 

technische Anlage Version 10, Stand 18.02.2016, anzuwenden ab 01.07.2017. Hinweis: Für die Technische Anlage 3 Version 9 Stand 26.09.2014 gilt eine Übergangsfrist von 3 Monaten, d.h. zum 01.10.2017 verliert diese ihre Gültigkeit. Daten werden ab diesem Datum nur noch im Format der Version 10 Stand 18.02.2016 angenommen.

**Comment by frschaul** [comment]
Ich habe dies exemplarisch bei uns in der tinyheb Version angepasst. Es befindet sich nun im produktiven Test bei meiner Frau.

**Comment by buzz** [comment]
@frschaul Super!
Könntest du den Code in einem geforkten Repository pushen und hier linken? Das wäre dufte!
Danke! :)

**Comment by frschaul** [comment]
Sorry, weiß leider nicht, wie das gehen soll. Bekomme beim File Upload immer:

Uploads are disabled.
File uploads require push access to this repository.

**Comment by danielrheinbay** [comment]
@buzz Kannst Du @frschaul in die tinyHeb-Organisation aufnehmen? Alternativ kannst Du mich zum Owner befördern, dann kümmere ich mich drum :)

@frschaul Alternativ kannst Du Dir Deinen eigenen Fork des Repositories erstellen, dort die Änderung pushen und dann einen Pull Request erstellen. Das Konzept ist beschrieben unter https://guides.github.com/introduction/flow/
Wenn Dir das zu kompliziert erscheint: schick mir Deine geänderten Dateien per Mail :)

**Comment by danielrheinbay** [comment]
Durch Anpassung an Heb_Edi.pm wie von Rolf vorgeschlagen gelöst.
